

// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as your changes will be overwritten.

// Get your Firebase configuration from the Firebase console.
// https://console.firebase.google.com/project/_/settings/general/

/**
 * Your web app's Firebase configuration.
 *
 * This object is used to initialize the Firebase app.
 * It is not a secret and can be safely embedded in your client-side code.
 *
 * @see https://firebase.google.com/docs/web/learn-more#config-object
 */
export const firebaseConfig = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
};
